### ISSUE TITLE
Stack.export() returns 404 due to double slash in url

### ISSUE THREAD

**Issue by oscardiedrichs** [docker/python-dockercloud#32]
```
import dockercloud
dockercloud.user = 'username'
dockercloud.apikey = 'apikey'
dockercloud.namespace = 'namespace'

test = dockercloud.Stack.export(dockercloud.Stack.fetch('uuid'))
```

Returns: 
`dockercloud.api.exceptions.ApiError: Status 404 (GET https://cloud.docker.com/api/app/v1/NAMESPACE/stack/UUID//export/). Response: {"error": "Not found"}`

Apparently it adds a slash / to the end in stack.py

```
class Stack(Mutable):
...
    def export(self):
       ...
        url = "/".join([self.resource_uri, "export"])
```
Debugging I can see that **self.resource_uri** already has a / at the end. 

Copying the 404 url and removing the double slash returns a correct json file.

**Comment by tifayuki** [comment]
fixed in the new version 1.0.11
Thank you
